#!/usr/bin/env python 
# -*- coding: utf-8 -*-
from sockets.server import Sockets
from gevent import monkey; monkey.patch_all()
import gevent.server, gevent.greenlet, gevent.pool
import config, tools, signal
import sys; reload(sys); sys.setdefaultencoding("utf-8")

def run():
  server_config = (config.Server.ip, config.Server.port)

  tools.log.info('Starting FyIRCd, listening on %s:%s' % server_config)
  pool   = gevent.pool.Pool(10000)
  server = gevent.server.StreamServer(server_config, Sockets.handle, spawn=pool, backlog=1024)

  server.serve_forever()

run()